---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates for ubuntu
    tags: always
    ansible.builtin.apt:
      upgrade: dist
      update-cache: yes
    when: ansible_distribution ==  "Ubuntu"

- hosts: Web_servers
  become: true
  tasks:

    - name: install apache on web servers
      tags: apache,ubuntu
      ansible.builtin.apt:
        name:
          - apache2
          - libapache2-mod-php
      when: ansible_distribution == "Ubuntu"

    - name: copy html file
      tags: apache,ubuntu
      ansible.builtin.copy:
        src: default-site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: '0644'
      when: ansible_distribution == "Ubuntu"

- hosts: DB_servers
  become: true
  tasks:

    - name: install mariadb
      tags: db, fedora
      ansible.builtin.dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "Fedora"
